# Generated by Django 3.0.2 on 2020-03-10 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='share_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='share',
            name='user_id',
            field=models.CharField(max_length=100),
        ),
    ]
