# Generated by Django 3.0.2 on 2020-03-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0004_auto_20200310_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='share_number',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
